/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    AButton: typeof import('@arco-design/web-vue')['Button']
    AButtonGroup: typeof import('@arco-design/web-vue')['ButtonGroup']
    ACol: typeof import('@arco-design/web-vue')['Col']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
    AOption: typeof import('@arco-design/web-vue')['Option']
    ARow: typeof import('@arco-design/web-vue')['Row']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ASlider: typeof import('@arco-design/web-vue')['Slider']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    ASwitch: typeof import('@arco-design/web-vue')['Switch']
    ATextarea: typeof import('@arco-design/web-vue')['Textarea']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    AUpload: typeof import('@arco-design/web-vue')['Upload']
    ControlledSlider: typeof import('./../src/components/controlled-slider/controlled-slider.vue')['default']
    IconDelete: typeof import('@arco-design/web-vue/es/icon')['IconDelete']
    IconDragArrow: typeof import('@arco-design/web-vue/es/icon')['IconDragArrow']
    IconEdit: typeof import('@arco-design/web-vue/es/icon')['IconEdit']
    IconEraser: typeof import('@arco-design/web-vue/es/icon')['IconEraser']
    IconEye: typeof import('@arco-design/web-vue/es/icon')['IconEye']
    IconEyeInvisible: typeof import('@arco-design/web-vue/es/icon')['IconEyeInvisible']
    IconFileImage: typeof import('@arco-design/web-vue/es/icon')['IconFileImage']
    IconFire: typeof import('@arco-design/web-vue/es/icon')['IconFire']
    IconFullscreen: typeof import('@arco-design/web-vue/es/icon')['IconFullscreen']
    IconFullscreenExit: typeof import('@arco-design/web-vue/es/icon')['IconFullscreenExit']
    IconLeftCircle: typeof import('@arco-design/web-vue/es/icon')['IconLeftCircle']
    IconLock: typeof import('@arco-design/web-vue/es/icon')['IconLock']
    IconMinus: typeof import('@arco-design/web-vue/es/icon')['IconMinus']
    IconObliqueLine: typeof import('@arco-design/web-vue/es/icon')['IconObliqueLine']
    IconPlus: typeof import('@arco-design/web-vue/es/icon')['IconPlus']
    IconRedo: typeof import('@arco-design/web-vue/es/icon')['IconRedo']
    IconRightCircle: typeof import('@arco-design/web-vue/es/icon')['IconRightCircle']
    IconUndo: typeof import('@arco-design/web-vue/es/icon')['IconUndo']
    IconUpload: typeof import('@arco-design/web-vue/es/icon')['IconUpload']
    Loading: typeof import('./../src/components/Loading/src/Loading.vue')['default']
    Navbar: typeof import('./../src/components/navbar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
